theme: jekyll-theme-dinky
show_downloads: false
title: "DAC WG: Auditing AI"
description: "Homepage for the Notre Dame Data, AI, and Computing working group on Socio-Technical Auditing of AI Systems"
